name: Run test suite

on: push

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        firefox: ['latest']
    name: Firefox ${{ matrix.firefox }} sample
    steps:
      - name: Setup firefox
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: ${{ matrix.firefox }}
          run: firefox --version

  tox:
    name: Run tox
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Run flask
        run: flask run --host=0.0.0.0
      - name: Test with tox
        run: tox -e func